name: Publish Workflow
on:
  push:
    branches:
    - master
jobs:
  Publish_Workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1.0.0
    - name: Prepare repository
      run: git checkout "${GITHUB_REF:11}"
    - name: Extract version
      id: extract_version
      run: |
        sudo apt-get install -y jq 
        echo "::set-output name=version::$(cat package.json | jq -r ".version")"
        echo "::set-output name=new_version::$(cat .VERSION)"
      env:
        VERSION: ${{ steps.extract_version.outputs.version }}
        NEW_VERSION: ${{ steps.extract_version.outputs.new_version }}
    - name: Publish
      if: steps.extract_version.outputs.version != steps.extract_version.outputs.new_version
      env:
        VERSION: ${{ steps.extract_version.outputs.version }}
        NEW_VERSION: ${{ steps.extract_version.outputs.new_version }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      uses: ./.github/workflows/publish/