name: Publish Workflow
on:
  push:
    branches:
    - master
jobs:
  Publish_Workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1.0.0
    - name: Prepare repository
      run: git checkout "${GITHUB_REF:11}"
    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq 
    - name: Extract version
      id: extract_version
      run:  echo "::set-output name=version::$(cat package.json | jq -r ".version")" && echo "::set-output name=new_version::$(cat .VERSION)"
    # - name: publish
    #   uses: ./.github/workflows/publish/
    #   if: steps['Extract version'].outputs.version != steps['Extract version'].outputs.new_version
    #   env:
    #     VERSION: ${{ steps.extract_version.outputs.version }}
    #     NEW_VERSION: ${{ steps.extract_version.outputs.new_version }}
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - name: test
      run: echo "$VERSION => $NEW_VERSION"
      env:
        VERSION: ${{ steps.extract_version.outputs.version }}
        NEW_VERSION: ${{ steps.extract_version.outputs.new_version }}
