name: Publish Workflow
on:
  push:
    branches:
    - master
jobs:
  Publish_Workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2-beta
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Extract version
      id: version
      run: |
        sudo apt-get install -y jq 
        NEW_VERSION=$(cat .VERSION) 
        if [ "$(cat package.json | jq -r ".version")" != "$NEW_VERSION" ]; then
          echo "::set-output name=new::$(echo $NEW_VERSION)"
        fi
    - name: Publish
      if: steps.version.outputs.new  
      env:
        NEW_VERSION: ${{ steps.version.outputs.new }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      # uses: ./.github/workflows/publish/
      run: |
        echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> ~/.npmrc

        git config --global user.name '(none)' && git config --global user.email 'noreply@github.com' && git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        npm install -g np
        npm install
        npm run build:dist
        npm run build:readme
        git add dist
        git add package-lock.json
        git add readme.md
        git commit -n -m "Built dist for $NEW_VERSION"
        echo "Updating to $NEW_VERSION"

        np $NEW_VERSION
        git push origin master
        git push --tags origin master
        exit 0