name: Publish Workflow
on:
  push:
    branches:
    - master
jobs:
  Publish_Workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2-beta
    - name: Extract version
      id: extract_version
      run: |
        sudo apt-get install -y jq 
        echo "::set-output name=version::$(cat package.json | jq -r ".version")"
        echo "::set-output name=new_version::$(cat .VERSION)"
      env:
        VERSION: ${{ steps.extract_version.outputs.version }}
        NEW_VERSION: ${{ steps.extract_version.outputs.new_version }}
    id: version
    run: |  
      if: steps.extract_version.outputs.version != steps.extract_version.outputs.new_version
      run: echo "::set-output name=new::$(cat .VERSION)"
      env:
        NEW_VERSION: ${{ steps.extract_version.outputs.new_version }}
    - name: Publish
      if: steps.version.outputs.new  
      env:
        NEW_VERSION: ${{ steps.version.outputs.new }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      uses: ./.github/workflows/publish/
    - name: Checkout2
      if: steps.version.outputs.new
      uses: actions/checkout@v2-beta
      with:
        ref: develop
    - name: Publish2
      if: steps.version.outputs.new
      run: |
        git pull origin master
        git push origin develop