name: Publish Workflow
on:
  push:
    branches:
    - master
jobs:
  Publish_Workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2-beta
    - name: Extract version
      id: version
      run: |
        sudo apt-get install -y jq 
        NEW_VERSION=$(cat .VERSION) 
        if [ "$(cat package.json | jq -r ".version")" != "$NEW_VERSION" ]; then
          echo "::set-output name=new::$(echo $NEW_VERSION)"
        fi
    - name: Publish
      if: steps.version.outputs.new  
      env:
        NEW_VERSION: ${{ steps.version.outputs.new }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      uses: ./.github/workflows/publish/